## ---- PORT ----
server:
  port: !!int 8080

## ---- Spring ----
spring:
  jpa: ## ---- Postgres ----
    database: POSTGRESQL
    hibernate: ## ---- Hibernate ddl auto ---- # (create, create-drop, validate, update, none)
      ddl-auto: create-drop
    show-sql: true  # ---- Show SQL ----

  datasource: ## ---- Spring DATASOURCE ----
    url: jdbc:postgresql://localhost:5432/spring_hiber?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mvc:
    hidden-method: ## ---- Hidden Method ----
      filter:
        enabled: true

  mail: ## ---- Mail ----
    host: smtp.gmail.com
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    port: !!int 587
    protocol: smtp
    debug: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

notifications: # ---- Попределяем число дней перед уведомлением админов о ДР пользователей ----
  users:
    birthday: !!int 5

api: # ---- Добавляем токены через переменные окружения для своих API ----
  port: !!int 8080 # да-да, повторяемся
  vk:
    tokenWithBearer: ${VK_API_TOKEN_WITH_BEARER}
    tokenWithoutBearer: ${VK_API_TOKEN}
    URL_CREATE_COMMENT: https://api.vk.com/method/wall.createComment
    URL_GET_COMMENTS: https://api.vk.com/method/wall.getComments
    URL_UPDATE_COMMENT: https://api.vk.com/method/wall.editComment
    URL_DELETE_COMMENT: https://api.vk.com/method/wall.deleteComment
    OWNER_ID: ${VK_API_OWNER_ID}
    POST_ID: 2
    PREVIEW_LENGTH: 0
    V: 5.131
  duck:
    URL_DUCK_API: https://random-d.uk/api/v2
    URL_FOR_RANDOM_DUCK: /random